chore(CI): fix failing playwright installation on e2e CI (#12450)
**Motivation**

Currently the playwright installation on CI fails with [following
error](https://github.com/react-navigation/react-navigation/actions/runs/13436891400/job/37541233565?pr=12449):

```
Package libasound2 is a virtual package provided by:
  liboss4-salsa-asound2 4.2-build2020-1ubuntu3
  libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)

E: Package 'libasound2' has no installation candidate
E: Unable to locate package libffi7
E: Unable to locate package libx264-163
Failed to install browsers
Error: Installation process exited with code: 100
Error: Process completed with exit code 1.
```

This is because playwright has some issues on newest ubuntu-24.04 (see
[issue on playwright
repo](https://github.com/microsoft/playwright/issues/30368)).

The CI started failing out of a sudden, because our CI is configured to
use `ubuntu-latest` and the switch from `22.04` to `24.04` must have
been done lately.

Support for `24.04` has been released with recent version of playwright.

**Test plan**

CI e2e should pass.